[build]
dockerfilePath = "Dockerfile"
builder = "DOCKERFILE"

[deploy]
startCommand = "bash /usr/local/bin/entrypoint.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckTimeout = 300
numReplicas = 1

[[services]]
name = "pg-1"
serviceType = "service"
domains = ["pg-1.railway.internal"]

[services.envs]
NODE_NAME = "pg-1"
NODE_ID = "1"
POSTGRES_PASSWORD = "${{POSTGRES_PASSWORD}}"
REPMGR_PASSWORD = "${{REPMGR_PASSWORD}}"
PEERS = "pg-2,pg-3"

[services.volumes]
source = "pg1_data"
path = "/var/lib/postgresql"

[[services]]
name = "pg-2"
serviceType = "service"
domains = ["pg-2.railway.internal"]

[services.envs]
NODE_NAME = "pg-2"
NODE_ID = "2"
POSTGRES_PASSWORD = "${{POSTGRES_PASSWORD}}"
REPMGR_PASSWORD = "${{REPMGR_PASSWORD}}"
PEERS = "pg-1,pg-3"

[services.volumes]
source = "pg2_data"
path = "/var/lib/postgresql"

[[services]]
name = "pg-3"
serviceType = "service"
domains = ["pg-3.railway.internal"]

[services.envs]
NODE_NAME = "pg-3"
NODE_ID = "3"
POSTGRES_PASSWORD = "${{POSTGRES_PASSWORD}}"
REPMGR_PASSWORD = "${{REPMGR_PASSWORD}}"
PEERS = "pg-1,pg-2"

[services.volumes]
source = "pg3_data"
path = "/var/lib/postgresql"

[[services]]
name = "pg-4"
serviceType = "service"
domains = ["pg-4.railway.internal"]

[services.envs]
NODE_NAME = "pg-4"
NODE_ID = "4"
POSTGRES_PASSWORD = "${{POSTGRES_PASSWORD}}"
REPMGR_PASSWORD = "${{REPMGR_PASSWORD}}"
PEERS = "pg-1,pg-2"

[services.volumes]
source = "pg4_data"
path = "/var/lib/postgresql"

[[services]]
name = "witness"
serviceType = "service"
domains = ["witness.railway.internal"]

[services.envs]
NODE_NAME = "witness"
NODE_ID = "99"
IS_WITNESS = "true"
REPMGR_PASSWORD = "${{REPMGR_PASSWORD}}"
PRIMARY_HOST = "pg-1"
PEERS = "pg-1,pg-2,pg-3"

# Không cần volume cho witness vì nó không chạy PostgreSQL cluster