# ============================================================================
# Loki Configuration - Log Aggregation
# ============================================================================

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

# Ingester configuration
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h
  chunk_target_size: 1048576  # 1MB
  chunk_encoding: snappy
  
  wal:
    enabled: true
    dir: /loki/wal

# Storage schema configuration
schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Storage configuration (local filesystem)
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  
  filesystem:
    directory: /loki/chunks

# Limits configuration
limits_config:
  # Ingestion limits
  ingestion_rate_mb: 50  # 50MB/sec per tenant
  ingestion_burst_size_mb: 100
  
  # Query limits
  max_query_series: 10000
  max_query_parallelism: 32
  max_streams_per_user: 100000
  max_global_streams_per_user: 500000
  
  # Retention
  retention_period: 30d  # Keep logs for 30 days
  
  # Per-stream rate limits
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB
  
  # Cardinality limits
  max_label_names_per_series: 30
  max_label_name_length: 1024
  max_label_value_length: 2048

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 30d

# Table manager configuration
table_manager:
  retention_deletes_enabled: true
  retention_period: 30d

# Compactor configuration
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Query frontend configuration
query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 500

# Ruler configuration (for alerts based on logs)
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  
  enable_api: true
  enable_alertmanager_v2: true
