# ============================================================================
# Mimir Configuration - Long-term Metrics Storage (FIXED v2.11.0)
# ============================================================================

target: all
multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: info

distributor:
  pool:
    health_check_ingesters: true
  ring:
    kvstore:
      store: memberlist

ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks
  
  bucket_store:
    sync_dir: /data/tsdb-sync
  
  tsdb:
    dir: /data/tsdb
    retention_period: 2160h  # 90 days in hours

compactor:
  data_dir: /data/compactor
  sharding_ring:
    kvstore:
      store: memberlist

store_gateway:
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: memberlist

ruler:
  rule_path: /data/rules
  ring:
    kvstore:
      store: memberlist
  enable_api: false

# Minimal limits - only valid fields for v2.11.0
limits:
  ingestion_rate: 100000
  ingestion_burst_size: 200000
  max_query_parallelism: 32
  max_global_series_per_user: 5000000
