# ============================================================================
# Tempo Configuration - Distributed Tracing (FIXED for v2.3.1)
# ============================================================================

server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
    zipkin:
      endpoint: 0.0.0.0:9411
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1048576
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks
    
    block:
      bloom_filter_false_positive: 0.05
      # Removed: index_downsample_bytes, encoding - not valid in v2.3.1
    
    pool:
      max_workers: 100
      queue_depth: 10000

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1073741824
  trace_by_id:
    duration_slo: 5s

# Simplified metrics generator config for v2.3.1
metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: pg_ha_cluster
  
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/push
        send_exemplars: true
  
  # Simplified processor config (no 'enabled' field in v2.3.1)
  processor:
    service_graphs:
      wait: 10s
      max_items: 10000
    
    span_metrics:
      dimensions:
        - http.method
        - http.status_code

overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics
